FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
#EXPOSE 80
#EXPOSE 443
#
ENV ASPNETCORE_URLS=http://+:8080;http://+:80;
ENV ASPNETCORE_ENVIRONMENT=Development

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["APICustomerControl/APICustomerControl.csproj", "APICustomerControl/"]
RUN dotnet restore "APICustomerControl/APICustomerControl.csproj"
COPY . .
WORKDIR "/src/APICustomerControl"
RUN dotnet build "APICustomerControl.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "APICustomerControl.csproj" -c Release -o /app/publish ##/p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "APICustomerControl.dll"]

